using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChestFiller : MonoBehaviour
{
    private GameObject chest;
    [SerializeField] private int numberOfItems; // Number of items to add to the chest
    private List<string> itemNamesPrefix = new List<string>
        {
        "Ancient", "Mystic", "Golden", "Silver", "Enchanted"
    };
    private List<string> itemNames = new List<string>
    { // names generated by A.I.
        "Sword", "Health Potion", "Mana Potion", "Gold Ring", "Treasure Map", "Ancient Scroll",
        "Magic Wand", "Spell Book", "Crystal Ball", "Elixir of Life", "Cloak of Invisibility"
    };
    private List<string> itemSuffix = new List<string>
    {
        "of Power", "of Wisdom", "of Agility", "of Strength", "of Protection"
    };
    // list of random descriptions for items
    private List<string> itemDescriptions = new List<string>
    {
        "A powerful item that grants its wielder immense strength.",
        "A potion that restores health and vitality.",
        "A magical wand that casts spells of great power.",
        "An ancient scroll containing secrets of the universe.",
        "A crystal ball that reveals hidden truths."
    };


    void Start()
    {
        chest = gameObject;
        if (chest != null)
        {
            ChestManager chestManager = chest.GetComponent<ChestManager>();
            if (chestManager != null && !chestManager.GetIsOpen())
            {
                // Initialize the items dictionary of the chestManager with some randomly named items and random amounts by creating SimpleBaseItem instances and than adding it to the dictionry with the AddItem method from the ChestManager.cs.
                for (int i = 0; i < numberOfItems; i++)
                {
                    string itemNameNew = itemNamesPrefix[Random.Range(0, itemNamesPrefix.Count)] + " " +
                                      itemNames[Random.Range(0, itemNames.Count)] + " " +
                                      itemSuffix[Random.Range(0, itemSuffix.Count)];

                    string itemDescription = itemDescriptions[Random.Range(0, itemDescriptions.Count)];

                    SimpleBaseItem newItem = new SimpleBaseItem(itemNameNew, itemDescription);

                    int amount = Random.Range(1, 10); // Random amount between 1 and 10
                    //Debug.Log("Adding item: " + newItem.itemName + " with amount: " + amount);
                    chestManager.AddItem(newItem, amount);
                }


                Debug.Log("Chest filled with items.");
            }
            else
            {
                Debug.LogError("ChestManager component not found on the chest GameObject.");
            }
        }
        else
        {
            Debug.LogError("Chest GameObject not found in the scene.");
        }

    }
}
