// Items enum created based on the Unity Asset Store package:
// RPG icons free starter pack
// https://assetstore.unity.com/packages/2d/gui/icons/rpg-icons-free-starter-pack-245521
// by icreatepixels
// Generated by Claude AI through image analysis and enumeration

[System.Serializable]
public enum Items
{
    Arrow_Basic,
    Bone_Skull,
    Bone_White,
    Book_Closed_Red,
    Bottle_Standard_Blue,
    Bottle_Standard_Empty,
    Bottle_Standard_Green,
    Bow_Wood1,
    Cape_Hood_Darkyellow,
    Crown_Gold,
    Fish_Green,
    Gem_Diamond_Red,
    Gold_Bars_Three,
    Gold_Coins_Many,
    Key_Silver,
    Leafs_Long,
    Mushroom_Big_Red,
    Necklace_Silver_Red,
    Pickaxe_Basic,
    Pouch_Leather_Small,
    Ring_Gold_Magic,
    Scroll_Map2,
    Shield_Basic_Metal,
    Silver_Bars,
    Silver_Coins_Many,
    Stone_Basic_Grey,
    Stone_Blocks_Grey,
    Sword_Basic4_blue,
    Sword_Basic_Blue,
    Twig_Green,
    Wood_Log,
    Wood_Log_Single_birch,
    Wood_Logs_Three,
    Wood_Stick
}